# Generated by Django 5.2.10 on 2026-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=250)),
                ('op2', models.CharField(max_length=250)),
                ('op3', models.CharField(max_length=250)),
                ('op4', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
