# Generated by Django 5.2.10 on 2026-03-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
                ('mobno', models.BigIntegerField()),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
